services:
  app:
    build:
      context: .
      dockerfile: Local.Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"  
    env_file:
      - .env  
    restart: unless-stopped 
    volumes:
      - ./:/app  
